{% set version = "0.9.10" %}

package:
  name: hyperion-fortran
  version: {{version}}

source:
  fn: Hyperion-{{version}}.tar.gz
  url: https://pypi.io/packages/source/h/hyperion/Hyperion-{{version}}.tar.gz
  md5: cf067467290b51e02ea7dd56815340f0

build:
  number: 2
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - hdf5
    - mpich
  run:
    - hdf5
    - mpich

test:
  files:
    - amr.rtin
    - car.rtin
    - cyl.rtin
    - oct.rtin
    - sph.rtin
    - vor.rtin

about:
  home: https://github.com/hyperion-rt/hyperion
  license: BSD 2-Clause
  summary: Hyperion Radiation Transfer Code

extra:
  recipe-maintainers:
    - astrofrog-conda-forge
