{% set version = "0.9.11" %}

package:
  name: hyperion-fortran
  version: {{ version }}

source:
  fn: Hyperion-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/h/hyperion/Hyperion-{{ version }}.tar.gz
  md5: bcbacd463810b9787eb99a2d82cc7224

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - hdf5 1.10.*
    - hdf5-static 1.10.*
    - mpich
  run:
    - hdf5 1.10.*
    - hdf5-static 1.10.*
    - mpich

test:
  files:
    - amr.rtin
    - car.rtin
    - cyl.rtin
    - oct.rtin
    - sph.rtin
    - vor.rtin

about:
  home: https://github.com/hyperion-rt/hyperion
  license: BSD-2-Clause
  license_file: LICENSE
  summary: Hyperion Radiation Transfer Code

extra:
  recipe-maintainers:
    - astrofrog
