travis:
  secure:
    BINSTAR_TOKEN: zJ9mxFw7E2D6Aln27VQts8OD+SKrUx3lEwOmPeQgfi5z7kDBQQQIylkaSQcu+WKsXLZa2SGMFlmqJJ7MjrsCySGtmcVuO5gbD1pgXud37THJknkVPRADlmKfS4Vo/uDIG3u4wcdwoo3oVFBKlBTAQIZ+LBP+dPMQT+STRqGFlb8fCIPQt5WRwkBEkc2WOCVQUiR+1gREK0xCSegAbw7kwapJtevkIWd8ulZ7Zi40Xugs5+8LVo0tLp1zXAid1M30m8ewSaYNSUrD7JgwzzF944DEMQ4CSl1EXo1jONqQELeYP8mKr5u9VvlNymwi0uZjsCiSXmgJYZlUjZQy2JQ9yhE9x5HBP7PIjKuJj5/vvS6TwM4MCcOCopdZHR0FzHS1wMMszrYRZ/jtlW2bkcJddoHbcENbgmkay7lG7g8+kUHst5MajG+4PkuWE/ihWYjqy+1I5vVITpZShMISGRfJr5Aui7NSz/PS/7IrkctrCTKOdXndYeBM46GHZ3xVx96WYPh0xIRCHBWGBQzerztc3IgBKIvYMAHgohNINNRKSksLgfrYbVDmjulPW6xM2iIpzNYs8edZWADm6zRtkFJVk+G211b/BlYq94dIiRyJ8AMgJtNfm9+/HJh8tjqzAuNdjl5i27wuSMNzH+qX8ZgFyPgTwT7sv0hoJypclr61A/E=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
